### ISSUE TITLE
LibreOffice documents type support

### ISSUE THREAD

**Issue by chytreg** [basecamp/activestorage-office-previewer#4]
I'm thinking about adjusting `ACCEPTABLE_CONTENT_TYPES` to support the native LibreOffice documents as well. Why did you add support for generating previews only from MicrosftOffice documents when you are using LibreOffice under the hood anyway?

**Comment by georgeclaghorn** [comment]
Our customers don’t use LibreOffice very heavily. PR welcome.

**Comment by chytreg** [comment]
thx, as a quick hack since `ACCEPTABLE_CONTENT_TYPES ` hasn't been frozen I did smth like that:
```
# config/initializers/office_previewer.rb
# Adjust OfficePreviewer to support LibreOffice documents as well
ActiveStorage::Previewer::OfficePreviewer::ACCEPTABLE_CONTENT_TYPES.concat(
  [
    "application/vnd.oasis.opendocument.text", # odt
    "application/vnd.oasis.opendocument.graphics", # odg
    "application/vnd.oasis.opendocument.presentation", # odp
    "application/vnd.oasis.opendocument.spreadsheet", # ods
    "application/vnd.oasis.opendocument.chart", # odc
    "application/vnd.oasis.opendocument.image", # odi
  ],
)
```

Think that these are most used but any from this list should work as well: https://github.com/LibreOffice/core/blob/master/sysui/desktop/solaris/mime.types

When I find enough strength to generate all the sample files for test purpose will open a PR ;)
