### ISSUE TITLE
soffice --headless vs unoconv

### ISSUE THREAD

**Issue by chytreg** [basecamp/activestorage-office-previewer#5]
When making research about previews, first I have found this gist: https://gist.github.com/zealot128/5534cb70a06dcce96dba1fea7274fae5

Have you any rationale in favor of/against using `soffice --headless` vs `unoconv`?

**Comment by georgeclaghorn** [comment]
Wasn’t specifically considered. I needed something and `soffice --headless` was the first thing I found.

That gist goes .docx → .pdf → .png. This previewer goes straight from .docx to .png.
